config/routes.rb
AuditingProject::Application.routes.draw do
  
  resources :companies do
    resources :employments, :except => [:index, :show]
  end
  
  resources :people do
    resources :employments, :except => [:index, :show]
  end

  root :to => "companies#index"
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :industry
  
  has_many :phone_numbers, :as => :phoneable, :dependent => :destroy
  
  has_many :employments
  has_many :people, :through => :employments
  
  audit_enabled
  
  accepts_nested_attributes_for :phone_numbers,
    :reject_if => proc { |ph| ph['number'].blank? },
    :allow_destroy => true
  
  def to_label
    name
  end
  
end

app/models/employment.rb
class Employment < ActiveRecord::Base
  
  belongs_to :person
  belongs_to :company
  
  audit_relationship_enabled
  
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :companies
  
  def to_label
    name
  end
end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :phone_numbers, :as => :phoneable, :dependent => :destroy
  
  has_many :employments
  has_many :companies, :through => :employments
  
  audit_enabled :fields => [:first_name, :last_name]
  
  accepts_nested_attributes_for :phone_numbers,
    :reject_if => proc { |ph| ph['number'].blank? },
    :allow_destroy => true
  
  def to_label
    [last_name, first_name].join(', ')
  end
  
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :phoneable, :polymorphic => true
  audit_relationship_enabled
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end
  
  def show
    @company = Company.find(params[:id])
  end
  
  def new
    @company = Company.new
  end
  
  def create
    # render :text => params.inspect
    @company = Company.new(params[:company])
    if @company.save
      flash[:notice] = 'Company created'
      redirect_to @company
    else
      render :new
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    # render :text => params.inspect
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      flash[:notice] = 'Company updated'
      redirect_to @company
    else
      render :edit
    end
  end
  
  def destroy
    Company.destroy(params[:id])
    flash[:notice] = 'Company destroyed'
    redirect_to companies_path
  end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController

  def new
    @resource   = get_proper_resource(params)
    @employment = @resource.employments.build
  end
  
  def create
    # render :text => params.inspect
    @resource   = get_proper_resource(params)
    @employment = @resource.employments.build(params[:employment])
    if @employment.save
      flash[:notice] = 'Employment created'
      redirect_to @resource
    else
      render :new
    end
  end
  
  def edit
    @resource = get_proper_resource(params)
    @employment = Employment.find(params[:id])
  end
  
  def update
    @resource = get_proper_resource(params)
    @employment = Employment.find(params[:id])
    if @employment.update_attributes(params[:employment])
      flash[:notice] = 'Employment updated'
      redirect_to @resource
    else
      render :edit
    end
  end
  
private
  
  def get_proper_resource(params)
    if params[:company_id]
      Company.find(params[:company_id])
    else 
      Person.find(params[:person_id])
    end
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end
  
  def show
    @person = Person.find(params[:id])
  end
  
  def new
    @person = Person.new
  end
  
  def create
    # render :text => params.inspect
    @person = Person.new(params[:person])
    if @person.save
      flash[:notice] = 'Person created'
      redirect_to @person
    else
      render :new
    end
  end
  
  def edit
    @person = Person.find(params[:id])
  end
  
  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      flash[:notice] = 'Person updated'
      redirect_to @person
    else
      render :edit
    end
  end
  
  def destroy
    Person.destroy(params[:id])
    flash[:notice] = 'Person destroyed'
    redirect_to people_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def remove_child_link(name, f)
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", :class => "remove_child")
  end
  
  def add_child_link(name, association)
    link_to(name, "javascript:void(0)", :class => "add_child", :"data-association" => association)
  end
  
  def new_child_fields_template(form_builder, association, options = {})
    options[:object] ||= form_builder.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize
    options[:form_builder_local] ||= :f
    
    content_tag(:div, :id => "#{association}_fields_template", :style => "display: none") do
      form_builder.fields_for(association, options[:object], :child_index => "new_#{association}") do |f|
        render(:partial => options[:partial], :locals => {options[:form_builder_local] => f})
      end
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |form| %>
  
  <div class='form_items'>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>
  
    <p>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </p>
  
    <p>
      <%= form.label :industry %>
      <%= form.select :industry_id, Industry.all.collect {|i| [ i.name, i.id ] }, { :include_blank => true } %>
    </p>
    
    <h3>Phone Numbers</h3>
    <%= form.fields_for :phone_numbers do |phone_form| %>
      <%= render :partial => 'partials/phone_number', :locals => { :f => phone_form } %>
    <% end %>
  
    <p><%= add_child_link "New Phone Number", :phone_numbers %></p>
    <%= new_child_fields_template(form, :phone_numbers, :partial => 'partials/phone_number')%>
  
    <p>
      <%= form.submit %> |
      <%= link_to 'back', companies_path%>
    </p>
  
  </div>
<% end %>

app/views/companies/edit.html.erb
<h2>Edit Company</h2>

<%= render 'form' %>

app/views/companies/index.html.erb
<h2>Companies</h2>

<%= link_to 'New Company', new_company_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Industry</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= company.industry.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h2>New Company</h2>

<%= render 'form' %>

app/views/companies/show.html.erb
<h2><%= @company.name %></h2>

<%= link_to 'back' , companies_path %> | 
<%= link_to 'edit', edit_company_path(@company) %> | 
<%= link_to 'audit log', audits_path('company', @company) %>

<p>
  Industry: <%= @company.industry.name %>
</p>

<p>
  <%= @company.description %>
</p>

Phone Numbers:
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Extension</th>
    </tr>
  </thead>
  <tbody>
    <% @company.phone_numbers.each do |ph| %>
      <tr>
        <td><%= ph.number%></td>
        <td><%= ph.extension%></td>
      </tr>
    <% end %>
  </tbody>
</table>

Employments <%= link_to 'create', new_company_employment_path(@company) %>
<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @company.employments.each do |e| %>
      <tr>
        <td><%= e.person.to_label %></td>
        <td><%= e.start_date.to_s %></td>
        <td><%= e.end_date.to_s %></td>
        <td>
          <%= link_to 'edit', edit_company_employment_path(@company, e)%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employments/_form.html.erb
<%= form_for [@resource, @employment] do |form| %>
  
  <div class='form_items'>
  
    <p>
      <%= form.label :start_date %>
      <%= form.date_select :start_date %>
    </p>
  
    <p>
      <%= form.label :end_date %>
      <%= form.date_select :end_date %>
    </p>
  
    <% if @resource.is_a?(Company) %>
      <p>
        <%= form.label :person %>
        <%= form.select :person_id, Person.all.collect {|p| [ p.to_label, p.id ] }, { :include_blank => true } %>
      </p>
    <% else %>
      <p>
        <%= form.label :company %>
        <%= form.select :company_id, Company.all.collect {|c| [ c.to_label, c.id ] }, { :include_blank => true } %>
      </p>
    <% end %>
  
    <p>
      <%= form.submit %> |
      <%= link_to 'cancel', @resource %>
    </p>
  
  </div>
  
<% end %>

app/views/employments/edit.html.erb
<h2>Edit Employment</h2>

<%= render 'form' %>

app/views/employments/new.html.erb
<h2>New Employment</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuditingProject</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p>
    Quick Nav:
    <%= link_to 'Companies', companies_path %> | 
    <%= link_to 'People', people_path %>
  </p>
  
  <%= yield %>

</body>
</html>

app/views/partials/_phone_number.html.erb
<div class="fields">
  <p>
    <%= f.label :number  %>
    <%= f.text_field :number %>
  </p>
  
  <p>
    <%= f.label :extension  %>
    <%= f.text_field :extension %>
  </p>
  <%= remove_child_link "remove", f %>
</div>

app/views/people/_form.html.erb
<%= form_for @person do |form| %>
  
  <div class='form_items'>
  
    <p>
      <%= form.label :first_name, 'First Name' %>
      <%= form.text_field :first_name %>
    </p>
  
    <p>
      <%= form.label :middle_name, 'Middle Name' %>
      <%= form.text_field :middle_name %>
    </p>
  
    <p>
      <%= form.label :last_name, 'Last Name' %>
      <%= form.text_field :last_name %>
    </p>
  
  
    <h3>Phone Numbers</h3>
    <%= form.fields_for :phone_numbers do |phone_form| %>
      <%= render :partial => 'partials/phone_number', :locals => { :f => phone_form } %>
    <% end %>
  
    <p><%= add_child_link "New Phone Number", :phone_numbers %></p>
    <%= new_child_fields_template(form, :phone_numbers, :partial => 'partials/phone_number')%>
  
    <p>
      <%= form.submit %> |
      <%= link_to 'back', people_path%>
    </p>
  
  </div>
<% end %>

app/views/people/edit.html.erb
<h2>Edit Person</h2>

<%= render 'form' %>

app/views/people/index.html.erb
<h2>People</h2>

<%= link_to 'New Person', new_person_path %>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.first_name, person %></td>
        <td><%= person.middle_name %></td>
        <td><%= person.last_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h2>New Person</h2>

<%= render 'form' %>

app/views/people/show.html.erb
<h2><%= @person.first_name %></h2>

<%= link_to 'back' , people_path %> | 
<%= link_to 'edit', edit_person_path(@person) %> | 
<%= link_to 'audit log', audits_path('person', @person) %>

<p>
  First Name: <%= @person.first_name %><br/>
  Middle Name: <%= @person.middle_name %><br/>
  Last Name: <%= @person.last_name %><br/>
</p>

Phone Numbers:
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Extension</th>
    </tr>
  </thead>
  <tbody>
    <% @person.phone_numbers.each do |ph| %>
      <tr>
        <td><%= ph.number%></td>
        <td><%= ph.extension%></td>
      </tr>
    <% end %>
  </tbody>
</table>


Employments <%= link_to 'create', new_person_employment_path(@person) %>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @person.employments.each do |e| %>
      <tr>
        <td><%= e.company.to_label %></td>
        <td><%= e.start_date.to_s %></td>
        <td><%= e.end_date.to_s %></td>
        <td>
          <%= link_to 'edit', edit_person_employment_path(@person, e)%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>